import Card from '@/app/components/Card';

const feeds = [
  {
    id: 1,
    title: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl quis tincidunt ultricies, nunc nisl ultricies nunc, vitae aliqua',
    createdAt: 'Mar 20, 2023',
    img: 'https://source.unsplash.com/random/300x300/?1',
    tags: ['Design', 'Accessibility'],
    author: {
      name: 'John Doe',
      avatar:
        'https://i.pinimg.com/originals/12/25/7c/12257c071a178a1bbe6ffab5863356cf.jpg'
    }
  },
  {
    id: 1,
    title: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl quis tincidunt ultricies, nunc nisl ultricies nunc, vitae aliqua',
    img: 'https://source.unsplash.com/640x480/?2',
    createdAt: 'Mar 20, 2023',
    tags: ['Design', 'Accessibility'],
    author: {
      name: 'John Doe',
      avatar:
        'https://i.pinimg.com/originals/12/25/7c/12257c071a178a1bbe6ffab5863356cf.jpg'
    }
  },
  {
    id: 1,
    title: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl quis tincidunt ultricies, nunc nisl ultricies nunc, vitae aliqua',
    img: 'https://source.unsplash.com/640x480/?3',
    createdAt: 'Mar 20, 2023',
    tags: ['Design', 'Accessibility'],
    author: {
      name: 'John Doe',
      avatar:
        'https://i.pinimg.com/originals/12/25/7c/12257c071a178a1bbe6ffab5863356cf.jpg'
    }
  },
  {
    id: 1,
    title: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl quis tincidunt ultricies, nunc nisl ultricies nunc, vitae aliqua',
    img: 'https://source.unsplash.com/640x480/?4',
    createdAt: 'Mar 20, 2023',
    tags: ['Design', 'Accessibility'],
    author: {
      name: 'John Doe',
      avatar:
        'https://i.pinimg.com/originals/12/25/7c/12257c071a178a1bbe6ffab5863356cf.jpg'
    }
  },
  {
    id: 1,
    title: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl quis tincidunt ultricies, nunc nisl ultricies nunc, vitae aliqua',
    img: 'https://source.unsplash.com/640x480/?5',
    createdAt: 'Mar 20, 2023',
    tags: ['Design', 'Accessibility'],
    author: {
      name: 'John Doe',
      avatar:
        'https://i.pinimg.com/originals/12/25/7c/12257c071a178a1bbe6ffab5863356cf.jpg'
    }
  },
  {
    id: 1,
    title: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl quis tincidunt ultricies, nunc nisl ultricies nunc, vitae aliqua',
    img: 'https://source.unsplash.com/640x480/?6',
    createdAt: 'Mar 20, 2023',
    tags: ['Design', 'Accessibility'],
    author: {
      name: 'John Doe',
      avatar:
        'https://i.pinimg.com/originals/12/25/7c/12257c071a178a1bbe6ffab5863356cf.jpg'
    }
  }
];

const Feeds = () => {
  return (
    <div className='bg-base-100 min-h-full'>
      <div className='container px-6 py-6 mx-auto'></div>
      <div className='text-center'>
        <h1 className='text-2xl font-semibold text-gray-800 capitalize lg:text-3xl dark:text-white'>
          Feeds
        </h1>

        <p className='max-w-lg mx-auto mt-4 text-gray-500'>
          Browse through the latest posts on the platform. Discover promts and
          images generated by users all around the app.
        </p>
      </div>
      <div className='flex flex-col lg:flex-row flex-wrap items-center justify-center py-10 gap-10 mx-5'>
        {feeds.map((feed) => (
          <Card feed={feed} />
        ))}
      </div>
    </div>
  );
};

export default Feeds;
